1. What does RGBA stand for?

In [ ]:
'''
RGBA  stands for Red, green, Blue, Alpha(transparency) color values ranging from 0, 255 in each color.
'''

2. From the Pillow module, how do you get the RGBA value of any images?

In [ ]:
#Answer
from PIL import Image
import numpy as np

img = Image.open("/content/download.jpeg") ## Here I took sample image For Code.
rgba_val = img.convert('RGBA')
print(np.array(rgba_val.getdata()))

# the above code will print the RGBA values of image as a array.

[[ 83 128 157 255]
 [ 83 128 157 255]
 [ 83 128 157 255]
 ...
 [ 58 102 127 255]
 [ 58 102 127 255]
 [ 58 102 127 255]]


3. What is a box tuple, and how does it work?

In [ ]:
'''
Answer:
box tuple (X, Y, W, H) is tuple Data that takes 4 values which referes the following:
1st value refers left-edge X co-ordinate.
2nd value refers top Y co-ordinate.
3rd value refers width.
4th value refers height.
These are used for cropping the image.

'''

4. Use your image and load in notebook then, How can you find out the width and height of an Image object?

In [ ]:
#Answer
from PIL import Image
img = Image.open("/content/download.jpeg")
print(img.size)  #size variable gives the width and height of the object.


(259, 194)


5. What method would you call to get Image object for a 100×100 image, excluding the lower-left quarter of it?

In [ ]:
'''
image_object.crop((0, 50, 50, 50))
inside crop object tuple of 4 values should be present.
'''

6. After making changes to an Image object, how could you save it as an image file?

In [ ]:
'''
Answer:
image_object.save('filename.png') ---> will save the image with the file name mentioned. 
'''

7. What module contains Pillow’s shape-drawing code?

In [ ]:
'''
Answer:
ImageDraw module contains methods to draw shapes on image ojects.
'''

8. Image objects do not have drawing methods. What kind of object does? How do you get this kind of object?

In [ ]:
'''
Answer:
ImageDraw Module has shape drawing methods for drawing shapes on image objects.
shapes like line(), rectangle(), ellipse() and polygon().

'''